name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    strategy:
      matrix:
        go-version: ["1.19", "1.20", "1.21.x"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          IMAGE_NAME="gidraff/testapi"
          TAG="${GITHUB_SHA::7}"  # Shorten commit SHA to 7 characters
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Update deployment.yaml
        run: |
          IMAGE_NAME="gidraff/testapi"
          TAG="${GITHUB_SHA::7}" 
          sed -i "s|\(image: $IMAGE_NAME:\)[^ ]*|\1$TAG|" infra/deployment.yaml
          git config --global user.name 'Gidraff'
          git config --global user.email ${{ secrets.EMAIL }}
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/Gidraff/test
          git add infra/deployment.yaml
          git commit -m "Update deployment.yaml"
          git push
