name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    strategy:
      matrix:
        go-version: ["1.19", "1.20", "1.21.x"]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Display Go version
        run: go version

      - name: Check out the repository
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update deployment.yaml
        run: |
          sed -i "s|\(image: ${{ env.IMAGE_NAME }}:\)[^ ]*|\1${{ github.sha }}|" infra/deployment.yaml
          git config --global user.name 'Gidraff'
          git config --global user.email ${{ secrets.EMAIL }}
          git add infra/deployment.yaml
          git commit -m "Update deployment.yaml"
          git push
